spring.application.name=GenAi
spring.ai.google.genai.api-key=AQ.Ab8RN6Lo93qf30qVgYRrt3Lz_qMXH9_-VJ9J6RjDHEzGQWj6vQ
spring.ai.google.genai.chat.model=gemini-3.6-flash
server.port=8081
weather.api.key=9358d679c6944b4e8a945457261409


